server:
  port: 9900
logging:
  level:
    root: info
spring:
#  data:
#    redis:
#      database: 0
#      host: 121.40.154.188
#      port: 6379
#      password: 1851811574LIhao
#      timeout: 2000
#      jedis:
#        pool:
#          #连接池最大连接数
#          max-active: 20
#          #连接池最大阻塞时间（-1表示无限制）
#          max-wait: -1
#          #连接池中的最大空闲连接
#          max-idle: 10
#          #连接池最小空闲连接
#          min-idle: 0
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
